version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
      - ./app/static:/code/app/static
      - ./uploads:/code/uploads
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db/recipe_db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'recipe_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data: